### ISSUE TITLE
Redis connection to unix-socket

### ISSUE THREAD

**Issue by pbeckmann** [skx/overseer#35]
Hello,
i really like this idea of monitoring systems. (I don't want any graphics etc. Just a mail or so if something is broken.)

I want to run the software on a shared host. So it would be cool to use a redis server over a unix socket. 

Unfortunately i didn't found a way to enable it. - Do i miss something?

Kind regards

**Comment by pbeckmann** [comment]
So i've just looked into the source and the upstream go-redis repository. Apparently the library enables the use of unix-sockets -> https://github.com/go-redis/redis/issues/3 

If you interested in it. I would implement it and open a pull request.

**Comment by skx** [comment]
Bear in mind this project __doesn't__ send emails when tests-fail, it just stores the results in redis (so you're screwed if redis fails on your monitoring host).   If you wanted to be notified of the failures you'd need to write a small script to look for the failure-messages, and send the email.

The [existing bridges](https://github.com/skx/overseer/tree/master/bridges) could be copied easily enough - I guess that for email you'd base it on the IRC bridge since that sends messages only on failure.

> I'll file a bug for an email-sending bridge.  Seems like a useful thing to add.

Finally if you're on a shared host I'd wonder if you'd be able to leave a long-running process running?  The `overseer worker` script basically has to run non-stop to fetch jobs from the queue and run the tests.  You could certainly add the `overseer enqueue` task to cron, to add new jobs to the queue.  But in my experience shared-hosts often dislike long-running daemons.

Anyway back to your issue.  Yes I'd be happy to accept an update that added support for redis-sockets.  I guess you'd need to add:

* `-redis-socket` to cmd_enqueue.go
* `-redis-socket` to cmd_worker.go

I imagine that if there is a path set that would override the default localhost:6379 setting - which I think has to be the default when no arguments are specified.

**Comment by skx** [comment]
> >I'll file a bug for an email-sending bridge. Seems like a useful thing to add.

Filed and fixed, via #36

**Comment by skx** [comment]
Closed in #37
